import Heading from "@theme/Heading";
import styles from "@site/src/css/resume.module.css";
import {RiDraftLine} from "react-icons/ri";

const publicationsData = [
  {
    authors: [
      {name: "Md Mehedi Hasan", bold: true},
      {name: "Md Sahjalal Mondol Nilay"},
      {name: "Nahid Hossain Jibon"},
      {name: "Rashedur M. Rahman"}
    ],
    title: "LULC changes to riverine flooding: A case study on the Jamuna River, Bangladesh using the multilayer perceptron model",
    link: "https://doi.org/10.1016/j.rineng.2023.101079",
    journal: "Results in Engineering 18 (2023): 101079",
    image: {
      src: "/img/graphical-abstract.webp",
      alt: "Picture of LULC changes to riverine flooding: A case study on the Jamuna River, Bangladesh using the multilayerperceptron"
    },
    details: [
      "Land-Use Land-Cover (LULC) was generated by supervised classification from Landsat 5 and Landsat 8 data.",
      "The land-use land-cover changes were aggregated in a Markov matrix for land-use land-cover change analysis.",
      "The Riverine Flood Potential Index (RFPI) was calculated using the Multilayer Perceptron (MLP) model for both 1990 and 2020.",
      "LULC changes and riverine flood potential changes were calculated using the total relative difference formula.",
      "Geographically Weighted Regression (GWR) derived a statistical correlation between LULC and riverine flood potential changes."
    ]
  },
];

export default function Publications() {
  return (
    <div className="container">
      <div className={styles.center__container}>
        <RiDraftLine size="24"/>
        <Heading as="h3"> Publications </Heading>
      </div>
      <ul className={styles.publication__main__list} style={{listStyleType: "decimal"}}>
        {publicationsData.map((pub, idx) => (
          <li key={idx}>
            <p>
              {pub.authors.map((author, i) => (
                <span key={i}>
                    {author.bold ? <strong>{author.name}*</strong> : author.name}
                  {i < pub.authors.length - 1 && ", "}
                  </span>
              ))}
              <br/>
              <a
                href={pub.link}
                target="_blank"
                rel="noopener"
              >
                <strong>{`“${pub.title}”`}</strong>
              </a>
              <br/>
              {pub.journal}
            </p>
            <img
              className={styles.publication__img}
              src={pub.image.src}
              alt={pub.image.alt}
            />
            <ul className={styles.timeline__bullet__list}>
              {pub.details.map((detail, j) => (
                <li key={j} className={styles.timeline__bullet__list__items}>
                  {detail}
                </li>
              ))}
            </ul>
          </li>
        ))}
      </ul>
    </div>
  );
}
