import {Anchor, Container, Divider, Group, Image, List, Modal, Space, Text, Title} from '@mantine/core';
import { RiDraftLine } from 'react-icons/ri';
import { useDisclosure } from '@mantine/hooks';

const Publications = () => {
  const [opened, { open, close }] = useDisclosure(false);

  const publicationDetails = [
    {
      title: 'LULC changes to riverine flooding: A case study on the Jamuna River, Bangladesh using the multilayer perceptron model',
      authors: 'Md Mehedi Hasan*, Md Sahjalal Mondol Nilay, Nahid Hossain Jibon, and Rashedur M. Rahman.',
      journal: 'Results in Engineering 18 (2023): 101079',
      link: 'https://doi.org/10.1016/j.rineng.2023.101079',
      image: '/graphical-abstract.webp',
      details: [
        'Land-Use Land-Cover (LULC) was generated by supervised classification from Landsat 5 and Landsat 8 data.',
        'The land-use land-cover changes were aggregated in a Markov matrix for land-use land-cover change analysis.',
        'The Riverine Flood Potential Index (RFPI) was calculated using the Multilayer Perceptron (MLP) model for both 1990 and 2020.',
        'LULC changes and riverine flood potential changes were calculated using the total relative difference formula.',
        'Geographically Weighted Regression (GWR) derived a statistical correlation between LULC and riverine flood potential changes.'
      ]
    }
  ];

  return (
    <Container size={'lg'}>
      <Group justify={'center'}>
        <Title order={3}>
          <Group>
            <RiDraftLine /> Publications
          </Group>
        </Title>
      </Group>
      <Space h={'lg'} />

      <List type={'ordered'} size={'sm'} spacing={3}>
        {publicationDetails.map((publication, index) => {
          const authors = publication.authors.split(', ').map((author, i) => (
            author.includes('*') ? <Text key={i} span fw={700}>{author}</Text> : <Text key={i} span>{author}</Text>
          ));
          return (
            <List.Item key={index}>
              <Text>{authors.reduce((prev, curr) => [prev, ', ', curr])}</Text>
              <Anchor href={publication.link} target={'_blank'}>
                <Text c={'blue.6'} fw={600}>
                  &#x201C;{publication.title}&#x201D;
                </Text>
              </Anchor>
              <Text> {publication.journal} </Text>
              <Modal
                size={'100%'}
                radius={'lg'}
                withCloseButton={false}
                opened={opened}
                onClose={close}
                centered
              >
                <Image src={publication.image} />
              </Modal>
              <Image radius={'lg'} src={publication.image} onClick={open} style={{ cursor: 'pointer' }} />
              <Space h={'xl'} />
              <List size={'sm'} spacing={3} listStyleType={'disc'}>
                {publication.details.map((detail, index) => (
                  <List.Item key={index}>{detail}</List.Item>
                ))}
              </List>
            </List.Item>
          );
        })}
      </List>
      <Space h={'xl'}/>
      <Divider my={'xl'}/>
    </Container>
  );
}

export default Publications;